version: "3"
services:
  web:
    build: .
    links:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql
    restart: always
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=paayco
    ports:
      - "32000:3306"
    volumes:
      - .:/docker-entrypoint-initdb.d/:ro
  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: php-my-admin
    ports:
      - "8081:80"
    links:
      - db
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306